sudo: false
language: java
services:
- docker
cache:
  directories:
  - $HOME/.cache
  - $HOME/.m2
dist: trusty
jdk:
  - openjdk8

script: 
  - mvn -P release-profile clean install

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $site-token
  on:
    branch: master
